name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --run

    - name: Run linting
      run: npm run lint:check

    - name: Build project
      run: npm run build

    - name: Create distribution archive
      run: |
        cd dist
        zip -r ../parcel-tracker-dist.zip .
        cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: parcel-tracker-dist.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}