name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean
      draft:
        description: 'Create as draft release'
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --run

    - name: Run linting
      run: npm run lint:check

    - name: Build project
      run: npm run build

    - name: Create distribution archive
      run: |
        cd dist
        zip -r ../parcel-tracker-dist.zip .
        cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: parcel-tracker-dist.zip
        tag_name: ${{ github.event.inputs.version || github.ref }}
        name: Release ${{ github.event.inputs.version || github.ref }}
        draft: ${{ github.event.inputs.draft || false }}
        prerelease: ${{ github.event.inputs.prerelease || false }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}